apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: devops
  template:
    metadata:
      namespace: default
      labels:
        run: devops
    spec:
      containers:
      - name: devops
        image: IMAGE_TAG
        imagePullPolicy: IfNotPresent
        ports: 
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            port: http
            path: /
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            port: http
            path: /
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
